version: "3.7"
services:
  reverse-proxy:
    image: nginx:1.17.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - scripts
    networks:
      - arkhn

  scripts:
    image: arkhn/cleaning-scripts:latest
    container_name: cleaning-scripts
    env_file: .env
    build: .
    ports:
      - 5000:5000
    networks:
      - arkhn

networks:
  arkhn:
    name: arkhn_network
